name: Update Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: '35 14 * * *'

jobs:
  update-readme:
    name: 更新 wakatime README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
