name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: 更新wakatime README
    runs-on: ubuntu-latest
    steps:
      - uses: DivinerSun/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIMEZONE: true
          SHOW_TITLE: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_COMMIT: true
          SHOW_LANGUAGE: true
          SHOW_EDITORS: true
          SHOW_OS: true
